# Generated by Django 5.1.1 on 2024-11-07 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Additional learning resources or links', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=600), help_text='Expected time to complete this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise',
            field=models.TextField(blank=True, help_text='Practice exercise for the lesson', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_content',
            field=models.TextField(blank=True, help_text='Main lesson content/text material', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.DurationField(blank=True, help_text='Duration of the video', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for lesson video content', null=True),
        ),
    ]
