# Generated by Django 5.1.1 on 2024-11-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabManagement', '0002_lesson_additional_resources_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('reading', 'Reading Material'), ('exercise', 'Practice Exercise')], default='reading', help_text='Type of lesson content', max_length=20),
        ),
    ]
