# Generated by Django 5.1.1 on 2024-11-12 10:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabManagement', '0005_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='LabManagement.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'lesson'], name='LabManageme_student_540115_idx'), models.Index(fields=['is_completed'], name='LabManageme_is_comp_486fab_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
